owner: VirtualBAW
repo: status-page

sites:
  - name: Website Frontend
    url: https://virtualbaw.com
  - name: vAMSYS Dashboard
    url: https://vamsys.io
  - name: Support System
    url: https://support.virtualbaw.com
  - name: Ventura Server
    url: http://46.101.0.90
    
assignees:
  - xKaelyn

status-website:
  cname: status.virtualbaw.com
  theme: ocean
  logoUrl: https://i.ibb.co/WDY663K/VB-Transparent.png
  name: VirtualBAW
  introTitle: "Welcome to the status page for VirtualBAW"
  introMessage: This page shows off the current status of the VirtualBAW services and any issues that may have happened recently.
  navbar:
    - title: Website
      href: https://virtualbaw.com
    - title: Community Discord Server
      href: https://discord.virtualbaw.com
    - title: Support
      href: mailto:support.virtualbaw.com
