# Change these first
owner: VirtualBAW # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: VirtualBAW Frontend
    url: https://virtualbaw.com
  - name: VirtualBAW Support System
    url: https://support.virtualbaw.com
  - name: VirtualBAW Ventura Server
    url: http://46.101.0.90

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.virtualbaw.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VirtualBAW
  introTitle: "Welcome to the status page for VirtualBAW"
  introMessage: This page shows off the current status of the VirtualBAW services and any issues that may have happened recently.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
